In [ ]:
import pandas as pd

df = pd.read_csv("penguins.csv")

In [ ]:
df.tail()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [ ]:
print(df.shape)

(344, 7)

In [ ]:
print(df.columns)

Index(['species', 'island', 'bill_length_mm', 'bill_depth_mm',
       'flipper_length_mm', 'body_mass_g', 'sex'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    object
 1   island             344 non-null    object
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                334 non-null    object
dtypes: float64(4), object(3)
memory usage: 18.9+ KB

In [ ]:
df.describe()

       bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g
count      342.000000     342.000000         342.000000   342.000000
mean        43.921930      17.151170         200.915205  4201.754386
std          5.459584       1.974793          14.061714   801.954536
min         32.100000      13.100000         172.000000  2700.000000
25%         39.225000      15.600000         190.000000  3550.000000
50%         44.450000      17.300000         197.000000  4050.000000
75%         48.500000      18.700000         213.000000  4750.000000
max         59.600000      21.500000         231.000000  6300.000000

In [ ]:
df[["species", "island", "body_mass_g"]]

    species     island  body_mass_g
0    Adelie  Torgersen       3750.0
1    Adelie  Torgersen       3800.0
2    Adelie  Torgersen       3250.0
3    Adelie  Torgersen          NaN
4    Adelie  Torgersen       3450.0
..      ...        ...          ...
339  Gentoo     Biscoe          NaN
340  Gentoo     Biscoe       4850.0
341  Gentoo     Biscoe       5750.0
342  Gentoo     Biscoe       5200.0
343  Gentoo     Biscoe       5400.0

[344 rows x 3 columns]

In [ ]:
df[df["island"] == "Biscoe"]

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
20,Adelie,Biscoe,37.8,18.3,174.0,3400.0,FEMALE
21,Adelie,Biscoe,37.7,18.7,180.0,3600.0,MALE
22,Adelie,Biscoe,35.9,19.2,189.0,3800.0,FEMALE
23,Adelie,Biscoe,38.2,18.1,185.0,3950.0,MALE
24,Adelie,Biscoe,38.8,17.2,180.0,3800.0,MALE
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [ ]:
df[df["body_mass_g"] > 5000]

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
221,Gentoo,Biscoe,50.0,16.3,230.0,5700.0,MALE
223,Gentoo,Biscoe,50.0,15.2,218.0,5700.0,MALE
224,Gentoo,Biscoe,47.6,14.5,215.0,5400.0,MALE
227,Gentoo,Biscoe,46.7,15.3,219.0,5200.0,MALE
229,Gentoo,Biscoe,46.8,15.4,215.0,5150.0,MALE
...,...,...,...,...,...,...,...
335,Gentoo,Biscoe,55.1,16.0,230.0,5850.0,MALE
337,Gentoo,Biscoe,48.8,16.2,222.0,6000.0,MALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [ ]:
df[df["body_mass_g"] > 5000]

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
221,Gentoo,Biscoe,50.0,16.3,230.0,5700.0,MALE
223,Gentoo,Biscoe,50.0,15.2,218.0,5700.0,MALE
224,Gentoo,Biscoe,47.6,14.5,215.0,5400.0,MALE
227,Gentoo,Biscoe,46.7,15.3,219.0,5200.0,MALE
229,Gentoo,Biscoe,46.8,15.4,215.0,5150.0,MALE
...,...,...,...,...,...,...,...
335,Gentoo,Biscoe,55.1,16.0,230.0,5850.0,MALE
337,Gentoo,Biscoe,48.8,16.2,222.0,6000.0,MALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE

In [ ]:
df["species"].value_counts()

species
Adelie       152
Gentoo       124
Chinstrap     68
Name: count, dtype: int64

In [ ]:
df["island"].unique()

array(['Torgersen', 'Biscoe', 'Dream'], dtype=object)

In [ ]:
df["sex"].nunique()

3

In [ ]:
df.loc[df["flipper_length_mm"].idxmax()]

species              Gentoo
island               Biscoe
bill_length_mm         54.3
bill_depth_mm          15.7
flipper_length_mm     231.0
body_mass_g          5650.0
sex                    MALE
Name: 283, dtype: object

In [ ]:
idx = df["body_mass_g"].idxmin()
print(idx)
print(df.loc[idx, "species"])

190
Chinstrap

In [ ]:
df.nsmallest(5, "flipper_length_mm")

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
28,Adelie,Biscoe,37.9,18.6,172.0,3150.0,FEMALE
20,Adelie,Biscoe,37.8,18.3,174.0,3400.0,FEMALE
122,Adelie,Torgersen,40.2,17.0,176.0,3450.0,FEMALE
30,Adelie,Dream,39.5,16.7,178.0,3250.0,FEMALE
31,Adelie,Dream,37.2,18.1,178.0,3900.0,MALE

In [ ]:
df[df["flipper_length_mm"].between(180, 210)]

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,MALE
...,...,...,...,...,...,...,...
296,Gentoo,Biscoe,47.5,14.2,209.0,4600.0,FEMALE
318,Gentoo,Biscoe,48.4,14.4,203.0,4625.0,FEMALE
326,Gentoo,Biscoe,41.7,14.7,210.0,4700.0,FEMALE
328,Gentoo,Biscoe,43.3,14.0,208.0,4575.0,FEMALE
329,Gentoo,Biscoe,48.1,15.1,209.0,5500.0,MALE

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df["sex"] = df["sex"].replace({
    "MALE": "male",
    "FEMALE": "female"
})

df.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female

In [ ]:
df["species_code"] = df["species"].map({
    "Adelie": 1,
    "Chinstrap": 2,
    "Gentoo": 3
})

df.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,species_code
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,1
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,1
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,1
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,1
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,1

In [ ]:
df["bill_ratio"] = df["bill_length_mm"] / df["bill_depth_mm"]

df.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,species_code,bill_ratio
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,1,2.090909
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,1,2.270115
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,1,2.238889
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,1,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,1,1.901554

In [ ]:
df.corr(numeric_only=True)["body_mass_g"].sort_values(ascending=False)

body_mass_g          1.000000
flipper_length_mm    0.871202
species_code         0.750491
bill_ratio           0.703119
bill_length_mm       0.595110
bill_depth_mm       -0.471916
Name: body_mass_g, dtype: float64

In [ ]:
df.isnull().sum()

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  10
species_code          0
bill_ratio            2
dtype: int64

In [ ]:
df[df["body_mass_g"].isna() & df["species"].notna()]

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,species_code,bill_ratio
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,1,NaN
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN,3,NaN

In [ ]:
df.dropna(thresh=5)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,species_code,bill_ratio
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,1,2.090909
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,1,2.270115
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,1,2.238889
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,1,1.901554
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,male,1,1.907767
...,...,...,...,...,...,...,...,...,...
338,Gentoo,Biscoe,47.2,13.7,214.0,4925.0,female,3,3.445255
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,female,3,3.272727
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,male,3,3.210191
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,female,3,3.054054
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,male,3,3.099379

In [ ]:
df["sex"] = df["sex"].fillna("Unknown")

In [ ]:
df["body_mass_g"] = df["body_mass_g"].fillna(df["body_mass_g"].mean())
df.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,species_code,bill_ratio
0,Adelie,Torgersen,39.1,18.7,181.0,3750.000000,male,1,2.090909
1,Adelie,Torgersen,39.5,17.4,186.0,3800.000000,female,1,2.270115
2,Adelie,Torgersen,40.3,18.0,195.0,3250.000000,female,1,2.238889
3,Adelie,Torgersen,NaN,NaN,NaN,4201.754386,Unknown,1,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.000000,female,1,1.901554