In [ ]:
import pandas as pd

df = pd.read_csv("penguins.csv")

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    object
 1   island             344 non-null    object
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                334 non-null    object
dtypes: float64(4), object(3)
memory usage: 18.9+ KB

In [ ]:
print("Unique species:", df["species"].nunique())
print("Unique islands:", df["island"].nunique())

Unique species: 3
Unique islands: 3

In [ ]:
df.groupby("species")["body_mass_g"].mean()

species
Adelie       3700.662252
Chinstrap    3733.088235
Gentoo       5076.016260
Name: body_mass_g, dtype: float64

In [ ]:
df.groupby("island")["flipper_length_mm"].mean()

island
Biscoe       209.706587
Dream        193.072581
Torgersen    191.196078
Name: flipper_length_mm, dtype: float64

In [ ]:
df.groupby("species")["bill_length_mm"].agg(["min", "max", "mean"])

            min   max       mean
species
Adelie     32.1  46.0  38.791391
Chinstrap  40.9  58.0  48.833824
Gentoo     40.9  59.6  47.504878

In [ ]:
df.groupby(["species", "island"])["body_mass_g"].count()

species    island
Adelie     Biscoe        44
           Dream         56
           Torgersen     51
Chinstrap  Dream         68
Gentoo     Biscoe       123
Name: body_mass_g, dtype: int64

In [ ]:
df.groupby("species")["body_mass_g"].mean().idxmax()

'Gentoo'

In [ ]:
df.groupby("island")["flipper_length_mm"].mean().sort_values(ascending=False)

island
Biscoe       209.706587
Dream        193.072581
Torgersen    191.196078
Name: flipper_length_mm, dtype: float64

In [ ]:
groups = df.groupby(["species", "island"]).size()

groups[groups >= 20]

species    island
Adelie     Biscoe        44
           Dream         56
           Torgersen     52
Chinstrap  Dream         68
Gentoo     Biscoe       124
dtype: int64

In [ ]:
df.groupby("species").agg({
    "body_mass_g": "mean",
    "flipper_length_mm": "mean"
})

           body_mass_g  flipper_length_mm
species
Adelie     3700.662252         189.953642
Chinstrap  3733.088235         195.823529
Gentoo     5076.016260         217.186992

In [ ]:
df.groupby("island").agg({
    "body_mass_g": ["count", "mean", "std"]
})

          body_mass_g
                count         mean         std
island
Biscoe            167  4716.017964  782.855743
Dream             124  3712.903226  416.644112
Torgersen          51  3706.372549  445.107940

In [ ]:
penguin_regions = pd.DataFrame({
    "island": ["Biscoe", "Dream", "Torgersen"],
    "region": ["Antarctica", "Antarctica", "Antarctica"]
})

merged_df = pd.merge(df, penguin_regions, on="island")

merged_df.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,region
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE,Antarctica
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE,Antarctica
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE,Antarctica
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,Antarctica
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE,Antarctica

In [ ]:
merged_df.groupby("region")["body_mass_g"].mean()

region
Antarctica    4201.754386
Name: body_mass_g, dtype: float64

In [ ]:
species_avg = df.groupby("species")["body_mass_g"].mean()

species_avg

species
Adelie       3700.662252
Chinstrap    3733.088235
Gentoo       5076.016260
Name: body_mass_g, dtype: float64

In [ ]:
overall_avg = df["body_mass_g"].mean()

overall_avg

np.float64(4201.754385964912)

In [ ]:
df["species_lower"] = df["species"].str.lower()

df.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,species_lower
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE,adelie
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE,adelie
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE,adelie
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,adelie
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE,adelie

In [ ]:
df["species_lower"].value_counts()

species_lower
adelie       152
gentoo       124
chinstrap     68
Name: count, dtype: int64

In [ ]:
penguin_observations = pd.DataFrame({
    "observation_date": [
        "2019-01-15",
        "2019-02-20",
        "2020-01-05",
        "2020-03-18"
    ]
})

penguin_observations

  observation_date
0       2019-01-15
1       2019-02-20
2       2020-01-05
3       2020-03-18

In [ ]:
penguin_observations["observation_date"] = pd.to_datetime(
    penguin_observations["observation_date"]
)

penguin_observations["year"] = penguin_observations["observation_date"].dt.year

penguin_observations

  observation_date  year
0       2019-01-15  2019
1       2019-02-20  2019
2       2020-01-05  2020
3       2020-03-18  2020

In [ ]:
penguin_observations["key"] = range(len(penguin_observations))
df["key"] = range(len(df))

merged = pd.merge(df, penguin_observations, on="key", how="left")

merged.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,species_lower,key,observation_date,year
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE,adelie,0,2019-01-15,2019.0
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE,adelie,1,2019-02-20,2019.0
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE,adelie,2,2020-01-05,2020.0
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,adelie,3,2020-03-18,2020.0
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE,adelie,4,NaT,NaN